Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'Shougo/neocomplete'
Plugin 'tomtom/tcomment_vim'
Plugin 'skwp/YankRing.vim'
Plugin 'tpope/vim-repeat'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
