Plugin 'tomtom/tcomment_vim'
Plugin 'skwp/YankRing.vim'
Plugin 'tpope/vim-repeat'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'altercation/vim-colors-solarized'
"Plugin 'Yggdroot/indentLine'
