git config --global alias.cob 'checkout -b'
git config --global branch.develop.mergeoptions '--no-ff'
alias ga='git add'
alias gs='git status'
alias gco='git checkout'
alias gpl='git pull'
alias gd='git diff'
alias gai='git add -i'
alias ga='git add'
