git config --global alias.cob 'checkout -b'
git config --global branch.develop.mergeoptions '--no-ff'
alias ga='git add'
alias gs='git status'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gpl='git pull'
alias gd='git diff'
alias grh='git reset --hard'
